export const convertCtoF = (temp: number) => temp * 1.8 + 32
export const convertFtoC = (temp: number) => (temp - 32) / 1.8

const stateCode: { [key: string]: string } = {
  ab: 'CA-AB',
  al: 'US-AL',
  ak: 'US-AK',
  ar: 'US-AR',
  as: 'US-AS',
  bc: 'CA-BC',
  ca: 'US-CA',
  co: 'US-CO',
  ct: 'US-CT',
  dc: 'US-DC',
  de: 'US-DE',
  fl: 'US-FL',
  ga: 'US-GA',
  gu: 'US-GU',
  hi: 'US-HI',
  id: 'US-iD',
  il: 'US-IL',
  in: 'US-IN',
  ia: 'US-IA',
  ks: 'US-KS',
  ky: 'US-KY',
  la: 'US-LA',
  ma: 'US-MA',
  mb: 'CA-MB',
  md: 'US-MD',
  me: 'US-ME',
  mi: 'US-MI',
  mn: 'US-MN',
  mo: 'US-MO',
  mp: 'US-MP',
  mt: 'US-MT',
  nb: 'CA-NB',
  nc: 'US-NC',
  nd: 'US-ND',
  ne: 'US-NE',
  nh: 'US-NH',
  nj: 'US-NJ',
  nl: 'CA-NL',
  nm: 'US-NM',
  ns: 'CA-NS',
  nt: 'CA-NT',
  nu: 'CA-NU',
  nv: 'US-NV',
  ny: 'US-NY',
  ok: 'US-OK',
  on: 'CA-ON',
  or: 'US-OR',
  pa: 'US-PA',
  pr: 'US-PR',
  sc: 'US-SC',
  sd: 'US-SD',
  sk: 'CA-SK',
  tn: 'US-TN',
  tx: 'US-TX',
  um: 'US-UM',
  ut: 'US-UT',
  va: 'US-VA',
  vi: 'US-VI',
  vt: 'US-VT',
  wa: 'US-WA',
  wi: 'US-WI',
  wv: 'US-WV',
  wy: 'US-WY',
  yt: 'CA-YT'
}

export const parseStateCode = (code: string): string =>
  stateCode[code.toLowerCase()] ?? code
